version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: eventflow_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: eventflow_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  nats:
    image: nats:2-alpine
    container_name: eventflow_nats
    restart: always
    ports:
      - "4222:4222"   # client connections
      - "8222:8222"   # monitoring HTTP
    command: ["-js"] # JetStream включён (если понадобится очереди/стримы)

volumes:
  postgres_data:
  redis_data: